src/objects/Change__c.object
<CustomObject>
    <fields>
        <fullName>AssignedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Change_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Highest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lowest</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Changes</relationshipLabel>
        <relationshipName>Changes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reopened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployment Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Change</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Fix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhancement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Feature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Change</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MobileDevice__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>DeviceToken__c</fullName>
        <label>Device Token</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeviceType__c</fullName>
        <inlineHelpText>&quot;ios&quot; or &quot;android&quot;</inlineHelpText>
        <label>Device Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <label>UserId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Mobile Device</label>
</CustomObject>

src/objects/MProject__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/IOSChangeNotificationService.cls
/*
 * Pushs notification to user's iOS devices when changes were updated
 */
public class IOSChangeNotificationService extends MobileNotificationService
{
    public override void push(List<Change__c> oldChanges, List<Change__c> newChanges)
    {
        Map<Id, Change__c> oldMap = getChangeId2Change(oldChanges);
        Map<Id, List<Id>> changeId2UserIds = getParentId2UserIdsByParentIds(oldMap.keySet());
        Set<Id> userIds = new Set<Id>();
        for(Id changeId : changeId2UserIds.keySet())
        {
            userIds.addAll(changeId2UserIds.get(changeId));
        }
        Map<String, List<String>> userId2DeviceTokens = getUserId2DeviceTokensByUserIds(userIds);
        Map<Id, List<String>> changeId2DeviceTokens = getParentId2DeviceTokens(changeId2UserIds, userId2DeviceTokens);
        
        NotificationInfo notification = new NotificationInfo(System.now(), true);
        for(Change__c change : newChanges)
        {
            String messageBody = composeChangeMessage(oldMap.get(change.Id), change);
            String backgroundMessage = composeChangeBackgroundMessage(change);
            if(changeId2DeviceTokens.containsKey(change.Id))
            {
                for(String deviceToken : changeId2DeviceTokens.get(change.Id))
                {
                    notification.Messages.add(new NotificationMessageInfo(messageBody, deviceToken, backgroundMessage));
                }
            }
        }
        pushNotification(notification);
    }
    
    public override Map<String, List<String>> getUserId2DeviceTokensByUserIds(Set<Id> userIds)
    {
        //android devices should be DeviceType__c = 'android'
        return getUserId2DeviceTokensByUserIdsAndType(userIds, 'ios');
    }
    
    public override void pushNotification(NotificationInfo notification)
    {
        sendHttpCalloutInFuture('http://184.72.226.199:8080/PushNotification/PushNotification', notification.generateJson());
    }
    
    @isTest
    static void testIOSChangeNotificationService()
    {
        String deviceToken = 'df9351db 69d1eab3 130c1b9c 5a7fb2c8 7edc0426 8ae3f1ae b37c2928 170f0f8c';
        List<User> users = [select Id, Name from User where IsEmployee__c = 1 and IsActive = true limit 2];
        MobileDevice__c mobileDevice = new MobileDevice__c(Name = users[0].Name, UserId__c = users[0].Id, DeviceToken__c = deviceToken, DeviceType__c = 'ios');
        insert mobileDevice;
        
        MProject__c project = new MProject__c(Name = 'acme');
        insert project;
        List<Change__c> changes = new List<Change__c>();
        changes.add(new Change__c(Name = 'acme1', Project__c = project.Id, AssignedTo__c = users[0].Id, Type__c = 'Change', Priority__c = 'Low', 
                                  Status__c = 'Open', DueDate__c = System.today(), Description__c = 'luffy'));
        changes.add(new Change__c(Name = 'acme2', Project__c = project.Id, AssignedTo__c = users[1].Id, Type__c = 'Task', Priority__c = 'Low', 
                                  Status__c = 'Open', DueDate__c = System.today(), Description__c = 'luffy'));
        insert changes;
        
        List<EntitySubscription> entitySubscriptions = new List<EntitySubscription>();
        entitySubscriptions.add(new EntitySubscription(ParentId = changes[0].Id, SubscriberId = users[0].Id));
        entitySubscriptions.add(new EntitySubscription(ParentId = changes[0].Id, SubscriberId = users[1].Id));
        entitySubscriptions.add(new EntitySubscription(ParentId = changes[1].Id, SubscriberId = users[0].Id));
        entitySubscriptions.add(new EntitySubscription(ParentId = changes[1].Id, SubscriberId = users[1].Id));
        insert entitySubscriptions;
        
        Test.startTest();
        Change__c change1 = changes[0];
        Change__c change2 = changes[1];
        change1.Name = 'test1';
        change2.Name = 'test2';
        changes.clear();
        changes.add(change1);
        changes.add(change2);
        update changes;
        Test.stopTest();
    }
}