src/objects/Change__c.object
<CustomObject>
    <label>Change</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/S3File__c.object
<CustomObject>
    <fields>
        <fullName>DownloadLink__c</fullName>
        <formula>HYPERLINK(&quot;http://www.meginfo.com/f/&quot; + SUBSTITUTE( Name , &quot;F&quot;, &quot;&quot;), &quot;http://www.meginfo.com/f/&quot; + SUBSTITUTE( Name , &quot;F&quot;, &quot;&quot;), &quot;_blank&quot;)</formula>
        <inlineHelpText>Generates download link, valid for 2 hours</inlineHelpText>
        <label>Download Link</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FileName__c</fullName>
        <label>File Name</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>OriginalDate__c</fullName>
        <inlineHelpText>The CreatedDate of the archived file</inlineHelpText>
        <label>Original Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <label>Parent Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Size__c</fullName>
        <formula>IF( SizeInBytes__c &gt; 1024 * 1024 * 1024, 
    TEXT(ROUND(SizeInBytes__c / 1024 / 1024 / 1024, 2)) + &apos;GB&apos;,
    IF(SizeInBytes__c &gt; 1024 * 1024,
       TEXT(ROUND(SizeInBytes__c / 1024 / 1024, 2)) + &apos;MB&apos;,
       IF(SizeInBytes__c &gt; 1024,
          TEXT(ROUND(SizeInBytes__c / 1024, 2)) + &apos;KB&apos;,
          TEXT(SizeInBytes__c) + &apos;B&apos;)
    )
)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Size</label>
        <type>Text</type>
    </fields>
    <label>S3 File</label>
    <nameField>
        <displayFormat>F{000000}</displayFormat>
        <label>File Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S3 Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/ChangeDetailController.cls
/*
 * Controller of page ChangeDetail
 */
public with sharing class ChangeDetailController 
{
    private Change__c change;
    
    public ChangeDetailController(ApexPages.StandardController controller) 
    {
        change = (Change__c)controller.getRecord();
    }
    
    public List<S3File__c> S3Files
    {
        get
        {
            return [select Id, Name, DownloadLink__c, FileName__c, Size__c, OriginalDate__c from S3File__c where ParentId__c=:change.Id];
        }
    }
    
    public PageReference redirect()
    { 
        return null;
    }

}