src/objects/Change__c.object
<CustomObject>
    <fields>
        <fullName>ChangeNumber__c</fullName>
        <displayFormat>{0000}</displayFormat>
        <label>Change #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Changes</relationshipLabel>
        <relationshipName>Changes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Change</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/FileType__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>ContentType__c</fullName>
        <label>ContentType</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>File Type Matrix</label>
</CustomObject>

src/objects/MProject__c.object
<CustomObject>
    <fields>
        <fullName>ProjectNumber__c</fullName>
        <displayFormat>Prj-{00000}</displayFormat>
        <label>Project Number</label>
        <type>AutoNumber</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PrivateKey__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Private Key</label>
</CustomObject>

src/objects/S3File__c.object
<CustomObject>
    <fields>
        <fullName>ContentType__c</fullName>
        <label>Content Type</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ParentId__c</fullName>
        <label>Parent Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3Bucket__c</fullName>
        <label>S3 Bucket</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3Key__c</fullName>
        <label>S3 Key</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SizeInBytes__c</fullName>
        <label>Size In Bytes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>S3 File</label>
    <nameField>
        <displayFormat>F{000000}</displayFormat>
        <label>File Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S3 Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/S3API.cls
/*
 * Includes helper methos for S3 interaction
 */
public class S3API
{
    @future(callout=true)
    public static void willRefreshFileSize(Id fileId)
    {
        List<S3File__c> files = [select S3Bucket__c, S3Key__c from S3File__c where Id=:fileId limit 1];
        if(files.size() > 0)
        {
            S3File__c file = files[0];
        	file.SizeInBytes__c = getFileSize(file.S3Bucket__c, file.S3Key__c);
        	update file;
        }
    }
    
    @future(callout=true)
    public static void willDeleteFiles(String bucket, Set<String> s3keys)
    {
        deleteFiles(bucket, s3keys);
    }
    
    public static Boolean putFile(String bucket, String s3key, String contentType, Blob body)
    {
        S3Request request = new S3Request('PUT', bucket, s3key);
        request.ContentType = contentType;
        request.Body = body;
        S3Response response = send(request);
        if(response != null)
        {
        	return response.StatusCode == 200;
        }
        else
        {
            return Test.isRunningTest();
        }
    }
    
    public static Long getFileSize(String bucket, String s3key)
    {
        S3Request request = new S3Request('HEAD', bucket, s3key);
        S3Response response = send(request);
        if(response != null)
        {
        	String sizeStr = response.Headers.get('Content-Length');
            System.debug('sizeStr=' + sizeStr);
        	if(String.isNotEmpty(sizeStr))
        	{
            	return Long.valueOf(sizeStr);
        	}
        }
        return -1;
    }
    
    public static void deleteFiles(String bucket, Set<String> s3keys)
    {
        S3Request request = new S3Request('POST', bucket, '', '?delete');
        String body = '<?xml version="1.0" encoding="UTF-8"?>' + 
						'<Delete>';
        for(String s3key : s3keys)
        {
			body += '<Object>' +
			           '<Key>' + EncodingUtil.urlDecode(s3key, 'utf-8') + '</Key>' +
                    '</Object>';
        }
        body += '</Delete>';
        request.ContentType = 'application/xml';
        request.Body = Blob.valueOf(body);
        request.ContentMD5 = EncodingUtil.base64Encode(Crypto.generateDigest('MD5', request.Body));
		S3Response response = send(request);
    }
    
    public static String getUrlToDownload(String bucket, String s3key)
    {
        String expiration = String.valueOf(DateTime.now().addHours(2).getTime() / 1000);
        String signature = sign('GET', null, null, expiration, bucket, s3key, null);
        String url = 'https://' + bucket + '.s3.amazonaws.com/' + s3key + '?AWSAccessKeyId=' + getAccessKey() + '&Signature=' + EncodingUtil.urlEncode(signature, 'utf-8') + '&Expires=' + expiration;
        return url;
    }
    
    //translates filename to s3key. format: projects//[project number]/[change number]/filename
    //e.g. projects/prj-0001/0011/document.txt
    //if the key is already existed, prepend a number, e.g. projects/prj-0001/0011/[2]document.txt
    public static String resolveS3Key(Id parentId, String filename)
    {
        String prefix = '';
        List<Change__c> changes = [select Id, ChangeNumber__c, Project__r.ProjectNumber__c from Change__c where Id=:parentId limit 1];
        if(changes.size() > 0)
        {
            prefix = 'projects/' + changes[0].Project__r.ProjectNumber__c + '/' + changes[0].ChangeNumber__c + '/';
        }
        else
        {
            List<MProject__c> projects = [select Id, ProjectNumber__c from MProject__c where Id=:parentId limit 1];
            if(projects.size() > 0)
            {
                prefix = 'projects/' + projects[0].ProjectNumber__c + '/';
            }
        }
        String result = prefix + EncodingUtil.urlEncode(filename, 'utf-8');
        Integer i = 1;
        while([select count() from S3File__c where ParentId__c=:parentId and S3Key__c=:result limit 1] > 0)
        {
            result = prefix + '[' + (++i) + ']' + EncodingUtil.urlEncode(filename, 'utf-8');
        }
        return result;
    }
    
    public static String resolveContentType(String filename)
    {
        Integer dotPosition = filename.lastIndexOf('.');
        String fileExtension = '';
        if(dotPosition > 0)
        {
            fileExtension = filename.substring(dotPosition, filename.length());
        }
        FileType__c fileType = FileType__c.getInstance(fileExtension.toLowerCase());
        if(fileType != null)
        {
            return fileType.ContentType__c;
        }
        else
        {
            return 'application/octet-stream';
        }
    }
    
    private static S3Response send(S3Request request)
    {
        if(String.isEmpty(request.Authorization))
        {
            String dateStr = DateTime.now().formatGmt('EEE, d MMM yyyy HH:mm:ss Z');
            request.Authorization = 'AWS ' + getAccessKey() + ':' + sign(request.HttpMethod, request.ContentMD5, request.ContentType, dateStr, request.Bucket, request.S3Key, request.SubResource);
            request.DateHeader = dateStr;
        }
        Http http = new Http();
        S3Response result = null;
        HTTPResponse response = null;
        try
        {
     		response = http.send(request.buildRequest());
            System.debug(response.getBody());
            result = new S3Response(response);
        }
        catch(Exception ex)
        {
            System.debug(ex.getMessage());
        }
        return result;
    }
    
    private static String sign(String httpMethod, String contentMD5, String contentType, String dateStr, String bucket, String s3key, String subresource)
    {
        contentMD5 = (contentMD5 == null) ? '' : contentMD5;
        contentType = (contentType == null) ? '' : contentType;
        subresource = (subresource == null) ? '' : subresource;
        String resource = '/' + bucket + '/' + s3key + subresource;
        String stringToSign = httpMethod + '\n' + contentMD5 + '\n' + contentType + '\n' + dateStr + '\n' + resource;
        System.debug('StringToSign=' + stringToSign);
        return sign(stringToSign);
    }
    
	private static String sign(String stringToSign)
    {
         return EncodingUtil.base64Encode(Crypto.generateMac('hmacSHA1', Blob.valueOf(stringToSign), Blob.valueOf(getSecretKey())));
    }
    
    private static String getAccessKey()
    {
        PrivateKey__c key = PrivateKey__c.getInstance('S3AccessKey');
        if(key != null)
        {
            return key.Key__c;
        }
        else
        {
            return null;
        }
    }
    
    private static String getSecretKey()
    {
        PrivateKey__c key = PrivateKey__c.getInstance('S3SecretKey');
        if(key != null)
        {
            return key.Key__c;
        }
        else
        {
            return null;
        }
    }
}