src/objects/Change__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Changes</relationshipLabel>
        <relationshipName>Changes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Change</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ChangeTask__c.object
<CustomObject>
    <fields>
        <fullName>Change__c</fullName>
        <label>Change</label>
        <referenceTo>Change__c</referenceTo>
        <relationshipLabel>Change Tasks</relationshipLabel>
        <relationshipName>ChangeTasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Change Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Change Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MProject__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TrelloSchedulerTest.cls
@isTest
private class TrelloSchedulerTest 
{
	@isTest static void testScheduler() 
	{
		TrelloUser__c testTrelloUser = new TrelloUser__c();
		testTrelloUser.Name = UserInfo.getUserId();
		testTrelloUser.Token__c = 'testToken';
		upsert testTrelloUser ;
		TrelloConfig__C testTrelloConfig = new TrelloConfig__c();
		testTrelloConfig.Key__c = 'testKey';
		upsert testTrelloConfig;
		List<MProject__c> testProjects = new List<MProject__c>();
		for(Integer i=0;i<10;i++)
		{
			MProject__c prj = TrelloTestFactory.createProject('testProject'+i);
			prj.TrelloBoardId__c = 'testTrelloBoardId'+i;
			testProjects.add(prj);
		}
		testProjects[2].TrelloBoardId__c = '545735a69a0da4e4721950fd';
		testProjects[5].TrelloBoardId__c = '5456dd656a8668e557b82685';
		upsert testProjects;

		Test.startTest();
		String CRON_EXP = '0 0 0 15 3 ? 2022';
		String jobId = System.schedule('TrelloSchedulerTest', CRON_EXP, new TrelloScheduler());
		TrelloConnectUtil testTrelloConnectUtil = new TrelloConnectUtil(testProjects);
		Test.setMock(HttpCalloutMock.class, new MockTrelloHttpResponseGenerator());
		MProject__c checkProject = [select Id from MProject__c where TrelloBoardId__c = '545735a69a0da4e4721950fd'];
		List<Change__c> testChanges = [select Id from Change__c where Project__c = :checkProject.Id];
		List<TeamMember__c> testTeamMembers = [select Id from TeamMember__c];
		List<ChangeTask__c> testChangeTasks = [select Id from ChangeTask__c];
		
		Test.stopTest();
		System.assertEquals(testChanges.size(), 1);
		System.assertNotEquals(testTeamMembers.size(), 0);
		System.assertNotEquals(testChangeTasks.size(), 0);
	}
}