src/objects/Change__c.object
<CustomObject>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Changes</relationshipLabel>
        <relationshipName>Changes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reopened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployment Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Change</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/MProject__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/PrivateKey__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Private Key</label>
</CustomObject>

src/objects/S3File__c.object
<CustomObject>
    <fields>
        <fullName>FileName__c</fullName>
        <label>File Name</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3Bucket__c</fullName>
        <label>S3 Bucket</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3Key__c</fullName>
        <label>S3 Key</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>S3 File</label>
    <nameField>
        <displayFormat>F{000000}</displayFormat>
        <label>File Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S3 Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/S3TestFixture.cls
/*
 * Includes test methods for s3 integration functionalities.
 */
@isTest
public class S3TestFixture
{
	@isTest
    static void testArchiveAttachment()
    {
        PrivateKey__c key1 = new PrivateKey__c(Name='S3AccessKey', Key__c='123');
        PrivateKey__c key2 = new PrivateKey__c(Name='S3SecretKey', Key__c='123');
        insert new List<PrivateKey__c> { key1, key2 };
            
        MProject__c prj = new MProject__c(Name='acme', Status__c='In Progress');
        insert prj;
        Change__c chg = new Change__c(Name='acme', Project__c=prj.Id, Status__c='Closed', DueDate__c=Date.today());
        insert chg;
        Attachment a = new Attachment(Name='acme', Body=Blob.valueOf('acme'), ParentId=chg.Id, ContentType='text/plain');
        insert a;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new S3CalloutMock());
        prj.Status__c = 'Closed';
        update prj;
        Test.stopTest();
    }
    
    @isTest
    static void testDeleteFile()
    {
        PrivateKey__c key1 = new PrivateKey__c(Name='S3AccessKey', Key__c='123');
        PrivateKey__c key2 = new PrivateKey__c(Name='S3SecretKey', Key__c='123');
        insert new List<PrivateKey__c> { key1, key2 };
        S3File__c file = new S3File__c(FileName__c='acme', S3Bucket__c='acme', S3Key__c='acme');
        insert file;
        
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new S3CalloutMock());
        delete file;
        Test.stopTest();
    }
    
    @isTest
    static void testRefreshFileSize()
    {
        PrivateKey__c key1 = new PrivateKey__c(Name='S3AccessKey', Key__c='123');
        PrivateKey__c key2 = new PrivateKey__c(Name='S3SecretKey', Key__c='123');
        insert new List<PrivateKey__c> { key1, key2 };
            
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new S3CalloutMock());
        S3File__c file = new S3File__c(FileName__c='acme', S3Bucket__c='acme', S3Key__c='acme');
        insert file;
        Test.stopTest();
    }
    
    @isTest
    static void testDownloadFile()
    {
        PrivateKey__c key1 = new PrivateKey__c(Name='S3AccessKey', Key__c='123');
        PrivateKey__c key2 = new PrivateKey__c(Name='S3SecretKey', Key__c='123');
        insert new List<PrivateKey__c> { key1, key2 };
         
        System.assert(S3API.getUrlToDownload('acme', 'acme') != null);
    }
    public class S3CalloutMock implements HttpCalloutMock
    {
		public HttpResponse respond(HttpRequest req) 
        {
            HttpResponse res = new HttpResponse();
            res.setHeader('Content-Type', 'application/json');
            res.setHeader('Content-Length', '20');
            res.setBody('{"foo":"bar"}');
            res.setStatusCode(200);
    		return res;
        }
    }
}