src/objects/Change__c.object
<CustomObject>
    <fields>
        <fullName>AssignedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Change_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ChangeNumber__c</fullName>
        <displayFormat>{0000}</displayFormat>
        <label>Change #</label>
        <type>AutoNumber</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>IsClosed__c</fullName>
        <description>1 represents the change is closed or cancelled</description>
        <formula>IF( TEXT( Status__c ) = &quot;Closed&quot; || TEXT( Status__c ) = &quot;Cancelled&quot;, 1, 0)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Is Closed</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Highest</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lowest</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Changes</relationshipLabel>
        <relationshipName>Changes</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reopened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployment Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Change</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Fix</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Enhancement</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Feature</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Task</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Change</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/ChangeTask__c.object
<CustomObject>
    <fields>
        <fullName>AssignedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Assigned To</label>
        <referenceTo>User</referenceTo>
        <relationshipName>ChangeTasks</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Change__c</fullName>
        <label>Change</label>
        <referenceTo>Change__c</referenceTo>
        <relationshipLabel>Change Tasks</relationshipLabel>
        <relationshipName>ChangeTasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>DueDate__c</fullName>
        <label>Due Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Estimation__c</fullName>
        <label>Estimation</label>
        <precision>11</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Change Task</label>
    <nameField>
        <label>Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Change Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LoginCredential__c.object
<CustomObject>
    <fields>
        <fullName>LoginURL__c</fullName>
        <label>Login URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Login Credentials</relationshipLabel>
        <relationshipName>LoginCredentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>SalesforceLoginURL__c</fullName>
        <formula>HYPERLINK(IF(AND($RecordType.Name = &quot;Salesforce&quot;, NOT(ISPICKVAL(Type__c, &quot;Portal&quot;))), &quot;https://&quot; + IF(ISPICKVAL(Type__c, &quot;Sandbox&quot;), &quot;test&quot;, &quot;login&quot;) + &quot;.salesforce.com/?un=&quot; + Username__c + &quot;&amp;pw=&quot; + Password__c, LoginURL__c), &quot;Log In&quot;, &quot;_self&quot;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Login URL</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sandbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free Edition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Login Credential</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Login Credentials</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MProject__c.object
<CustomObject>
    <fields>
        <fullName>Priority__c</fullName>
        <label>Priority</label>
        <picklist>
            <picklistValues>
                <fullName>Medium</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Low</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>High</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>LastActivityDate__c</fullName>
        <label>Last Activity Date</label>
        <summarizedField>TimeCard__c.Date__c</summarizedField>
        <summaryForeignKey>TimeCard__c.TeamMember__c</summaryForeignKey>
        <summaryOperation>max</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UI Designer</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>TotalHours__c</fullName>
        <label>Total Hours</label>
        <summarizedField>TimeCard__c.Hours__c</summarizedField>
        <summaryForeignKey>TimeCard__c.TeamMember__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TimeCard__c.object
<CustomObject>
    <fields>
        <fullName>Change__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Change</label>
        <referenceTo>Change__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>TimeCards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TeamMember__c</fullName>
        <label>Team Member</label>
        <referenceTo>TeamMember__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{0000000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/ProjectDetailController.cls
/*
 * Controller of page ProjectDetail
 */
public with sharing class ProjectDetailController
{
    private MProject__c prj;
    private List<Change__c> displayingChanges;
    private List<TeamMember__c> displayingMembers;

    public ProjectDetailController(ApexPages.StandardController ctrl)
    {
        prj = (MProject__c)ctrl.getRecord();
        List<TimeCard__c> lastTimeCards = [select Id, Date__c from TimeCard__c where Project__c=:prj.Id order by Date__c desc limit 1];
        ChartType = ''; //default to hide the time card charts
        if(lastTimeCards.size() > 0)
        {
            //if there are any time cards, show the pie chart
            ChartType = 'Percent';
            TimeCard__c lastTC = lastTimeCards[0];
            //if the last time card is in 10 months, show the monthly chart
            if(lastTC.Date__c >= Date.today().addDays(-310))
            {
                ChartType += ', Month';
            }
            //if the last time card is in 8 weeks, show the weekly chart
            if(lastTC.Date__c > Date.today().addDays(-56))
            {
                ChartType += ', Week';
            }
            if(lastTC.Date__c >= Date.today().addDays(-10))
            {
                ChartType += ', Day';
            }
        }

        //default to show all members.
        if(prj.Status__c == 'Closed')
        {
            ShowAllMembers = true;
        }
        else
        {
            ShowAllMembers = true;
        }
        ShowClosedChanges = false;
        ChangeSortingField = 'Status__c';
        ChangeSortingOrder = 'asc';
        OpenAllChanges = false;
    }

    public String SelectMemberId { get; set; }
    public String ChangeSortingField { get; set; }
    public String ChangeSortingOrder { get; set; }
    public Boolean OpenAllChanges { get; set; }

    public String Role
    {
        get
        {
            String result = '';
            String profileName = [select Name from Profile where Id=:UserInfo.getProfileId() limit 1].Name;
            if(profileName.toLowerCase().contains('admin'))
            {
                result = 'Administrator;';
            }
            if(prj.OwnerId == UserInfo.getUserId())
            {
                result += 'Owner;';
            }
            for(TeamMember__c member : [select Id, Role__c from TeamMember__c where Project__c=:prj.Id and User__c=:UserInfo.getUserId()])
            {
                result += member.Role__c;
            }
            return result;
        }
    }

    public Boolean HasPowerPrivilege { get { return Role.contains('Administrator') || Role.contains('Owner') || Role.contains('Manager'); } }

    public List<Change__c> Changes
    {
        get
        {
            if(displayingChanges == null)
            {
                Id prjId = prj.Id;
                String keyword = ChangeKeyword;
                String likeKeyword = '%' + ChangeKeyword + '%';
                String soql = 'select Id, Name, Priority__c, ChangeNumber__c, AssignedTo__c, AssignedTo__r.Name, Type__c, Status__c, DueDate__c, (select Name, Change__c, Estimation__c, Status__c, AssignedTo__c, AssignedTo__r.Name, DueDate__c from ChangeTasks__r where Name like :likeKeyword or Change__r.ChangeNumber__c like :likeKeyword or Status__c like :likeKeyword or AssignedTo__r.Name like :likeKeyword) from Change__c where Project__c=:prjId';                
                if(ChangeKeyword == null || ChangeKeyword.length() < 2)
                {
                   soql = 'select Id, Name, Priority__c, ChangeNumber__c, AssignedTo__c, AssignedTo__r.Name, Type__c, Status__c, DueDate__c, (select Name, Change__c, Estimation__c, Status__c, AssignedTo__c, AssignedTo__r.Name, DueDate__c from ChangeTasks__r) from Change__c where Project__c=:prjId';                
                }

                if(selectMemberId != null && selectMemberId != 'All' && selectMemberId != '')
                {
                    Set<Id> changeIds = new Set<Id>();
                    for(ChangeTask__c c : [select Change__c from ChangeTask__c where AssignedTo__c=:selectMemberId])
                    {
                        changeIds.add(c.Change__c);
                    }
                    soql = 'select Id, Name, Priority__c, ChangeNumber__c, AssignedTo__c, AssignedTo__r.Name, Type__c, Status__c, DueDate__c, (select Name, Change__c, Estimation__c, Status__c, AssignedTo__c, AssignedTo__r.Name, DueDate__c from ChangeTasks__r where AssignedTo__c=:selectMemberId) from Change__c where Project__c=:prjId and (AssignedTo__c=:selectMemberId or Id in:changeIds)';                
                }

                if(ChangeKeyword != null && ChangeKeyword.length() >= 2)
                {
                    Set<Id> changeIds2 = new Set<Id>();
                    for(ChangeTask__c c : [select Change__c, AssignedTo__r.Name from ChangeTask__c where Name like :likeKeyword or Change__r.ChangeNumber__c like :likeKeyword or Status__c like :likeKeyword or AssignedTo__r.Name like :likeKeyword])
                    {
                        changeIds2.add(c.Change__c);
                    }
                    //always includes the closed changes when there are keywords
                    soql += ' and ((Name like :likeKeyword or ChangeNumber__c like :keyword or Priority__c like :keyword or Type__c like :keyword or Status__c like :keyword or AssignedTo__r.Name like :likeKeyword) or Id in :changeIds2)';
                }

                if(!ShowClosedChanges)
                {
                    soql += ' and IsClosed__c=0';
                }
                soql += ' order by ' + ChangeSortingField + ' ' + ChangeSortingOrder;
                displayingChanges = Database.query(soql);
            }
            return displayingChanges;
        }
    }

    public Integer TotalChangeCount
    {
        get
        {
            return [select count() from Change__c where Project__c=:prj.Id];
        }
    }

    public Integer ClosedChangeCount
    {
        get
        {   Id prjId = prj.Id;
            String sql = 'select count() from Change__c where Project__c=:prjId and IsClosed__c=1';
            if(selectMemberId != null && selectMemberId != 'All' && selectMemberId != '')
            {
                 sql += ' and AssignedTo__c=:selectMemberId';
            }
            if(ChangeKeyword != null && ChangeKeyword.length() >= 2)
            {
                sql += ' and AssignedTo__r.Name like :ChangeKeyword';
            }
            return Database.countQuery(sql);
        }
    }

    public List<LoginCredential__c> LoginCredentials
    {
        get
        {
            return [select Id, Name, LoginUrl__c, SalesforceLoginURL__c, Type__c, RecordTypeId, RecordType.Name, Username__c, Password__c from LoginCredential__c where Project__c=:prj.Id];
        }
    }

    public List<TeamMember__c> TeamMembers
    {
        get
        {
            //sorting order: self, active members by role
            if(displayingMembers == null)
            {
                displayingMembers = new List<TeamMember__c>();
                for(TeamMember__c myself : [select Id, Name, Role__c, TotalHours__c, LastActivityDate__c, User__r.IsActive from TeamMember__c where Project__c=:prj.Id and User__c=:UserInfo.getUserId()])
                {
                    displayingMembers.add(myself);
                }
                List<TeamMember__c> members = [select Id, Name, Role__c, TotalHours__c, LastActivityDate__c, User__r.IsActive from TeamMember__c where Project__c=:prj.Id and User__c!=:UserInfo.getUserId() and User__r.IsActive=true order by Name desc];
                for(Schema.PicklistEntry roleEntry : TeamMember__c.Role__c.getDescribe().getPicklistValues())
                {
                    for(Integer i = members.size() - 1; i >= 0; i--)
                    {
                        if(members[i].Role__c != null && members[i].Role__c != '' && members[i].Role__c.indexOf(roleEntry.getValue()) >= 0)
                        {
                            displayingMembers.add(members[i]);
                            members.remove(i);
                        }
                    }
                }
                for(Integer i = members.size() - 1; i >= 0; i--)
                {
                    TeamMember__c memberWithNoRole = members[i];
                     displayingMembers.add(memberWithNoRole);
                }
            }
            return displayingMembers;
        }
    }

    public List<S3File__c> S3Files
    {
        get
        {
            return [select Id, Name, DownloadLink__c, FileName__c, Size__c, OriginalDate__c from S3File__c where ParentId__c=:prj.Id];
        }
    }

    public Integer AllMemberCount { get { return [select count() from TeamMember__c where Project__c=:prj.Id]; } }
    public Boolean ShowAllMembers { get; set; }
    public Boolean ShowClosedChanges { get; set; }
    public String ChangeKeyword { get; set; }
    public String ChartType { get; set; }

    public PageReference searchChanges()
    {
        displayingChanges = null;
        OpenAllChanges = true;
        return null;
    }

    public PageReference refresh()
    {
        displayingChanges = null;
        displayingMembers = null;
        OpenAllChanges = false;
        return null;
    }

    public PageReference refreshByMember()
    {
        displayingChanges = null;
        OpenAllChanges = true;
        return null;
    }

    @isTest
    static void testProjectdDtailController()
    {
        MProject__c p = new MProject__c(Name='acme');
        insert p;
        TeamMember__c member = new TeamMember__c(Project__c=p.Id, User__c=UserInfo.getUserId(), Role__c='Project Manager');
        insert member;
        Change__c chg = new Change__c(Project__c=p.Id, Status__c='Closed', DueDate__c=Date.today(), AssignedTo__c=UserInfo.getUserId());
        insert chg;

        ApexPages.StandardController ctrl = new ApexPages.StandardController(p);
        ProjectDetailController controller = new ProjectDetailController(ctrl);

        List<Change__c> changes = controller.Changes;
        System.assertEquals(0, changes.size());

        controller.ShowClosedChanges = true;
        controller.refresh();
        changes = controller.Changes;
        System.assertEquals(1, changes.size());
        Integer i = controller.TotalChangeCount;
        Integer j = controller.ClosedChangeCount;

        String role = controller.Role;
        System.assert(controller.HasPowerPrivilege);

        List<LoginCredential__c> ls = controller.LoginCredentials;

        List<TeamMember__c> members = controller.TeamMembers;
        System.assertEquals(1, members.size());
        System.assertEquals(1, controller.AllMemberCount);
    }
}