src/objects/Change__c.object
<CustomObject>
    <fields>
        <fullName>AssignedTo__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Owner</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Change_Management</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Reopened</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Waiting for Information</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Testing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Testing Passed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ready for Deployment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Deployment Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Change</label>
    <nameField>
        <label>Subject</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Changes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TimeCard__c.object
<CustomObject>
    <fields>
        <fullName>Change__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Change</label>
        <referenceTo>Change__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TeamMember__c</fullName>
        <label>Team Member</label>
        <referenceTo>TeamMember__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{0000000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DailyTimeCardReportControllerTest.cls
@isTest(seeAllData=true)
public class DailyTimeCardReportControllerTest
{
    static testmethod void testDailyTimeCardReportController()
    {
        List<Id> userIds = new List<Id>();
        for(Change__c change : [select Id, AssignedTo__c from Change__c where Status__c != 'closed' and Status__c != 'Cancelled'])
        {
            userIds.add(change.AssignedTo__c);
        }

        List<AggregateResult> aggResults = [select TeamMember__r.User__c u, sum(Hours__c) h, Date__c d from TimeCard__c
                                         where TeamMember__r.User__c in :userIds and Date__c <= :Date.today() and Date__c >= :Date.today().addDays(-6)
                                          group by TeamMember__r.User__c, Date__c limit 1];

        DailyTimeCardReportController controller = new DailyTimeCardReportController();
        controller.UserId = String.valueOf(aggResults[0].get('u'));
        String name = controller.UserFullName;
        Decimal totalHours = controller.TotalHours;
        List<DailyTimeCardReportController.ChangeInfo> changes = controller.Changes;

        Test.startTest();
        // Set mock callout class
        Test.setMock(HttpCalloutMock.class, new MockFinanceHttpResponseGenerator());
        ChartTable teamMembers = controller.MyMembers;
        Test.stopTest();
    }

}