src/objects/Credit__c.object
<CustomObject>
    <description>save credit data from the finance system temporarily.</description>
    <fields>
        <fullName>AdjustmentValue__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Adjustment Value</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Employee__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Look up to User object.</description>
        <label>Employee</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Credits</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>3</precision>
        <scale>1</scale>
        <type>Number</type>
    </fields>
    <label>Credit</label>
    <nameField>
        <label>Credit Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Credits</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CreditsSummaryController.cls
/*
 * summarize all user's credits.
 */
public class CreditsSummaryController
{
    public CreditsSummaryController()
    {
		AllCredits = [select Employee__c, Employee__r.Name, Value__c, AdjustmentValue__c from Credit__c order by Value__c Desc];
    }
    
    public Decimal MaxCreditValue
    {
    	get
        {
            Decimal max = 0;
        	for(Credit__c credit : AllCredits)
            {
                max = credit.Value__c > max ? credit.Value__c : max;
            }
            return max;
        }
    }
    public List<Credit__c> AllCredits { get; set; }    
}