src/objects/LoginCredential__c.object
<CustomObject>
    <fields>
        <fullName>LastSyncDate__c</fullName>
        <label>Last Sync Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>50</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Login Credentials</relationshipLabel>
        <relationshipName>LoginCredentials</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>ScmName__c</fullName>
        <label>SCM Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SyncError__c</fullName>
        <label>Sync Error</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Production</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Sandbox</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Free Edition</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Portal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Login Credential</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Login Credentials</pluralLabel>
    <recordTypes>
        <fullName>Salesforce</fullName>
        <active>true</active>
        <label>Salesforce</label>
    </recordTypes>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/MProject__c.object
<CustomObject>
    <fields>
        <fullName>ScmName__c</fullName>
        <label>SCM Name</label>
        <length>50</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/SourceCodeManagementController.cls
/*
 * Controller of page SourceCodeManagement
 */
public with sharing class SourceCodeManagementController 
{
    private MProject__c project;

    public SourceCodeManagementController(ApexPages.StandardController controller) 
    {
        //ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.WARNING, 'test'));
        project = (MProject__c)controller.getRecord();
        ProjectSyncing = (project.ScmName__c != null) && (project.ScmName__c != '');
        Branches = [select Id, Name, Type__c, ScmName__c, Sync__c, SyncError__c, LastSyncDate__c from LoginCredential__c where Project__c=:project.Id and RecordType.Name='Salesforce'];
    }
    
    public Boolean ProjectSyncing { get; set; }
    public List<LoginCredential__c> Branches { get; set; }
    public Boolean UserCanEdit
    {
        get
        {
            //User currentUser = [select Id, Profile.Name from User where Id=:UserInfo.getUserId() limit 1];
            //return (currentUser.Profile.Name == 'Force.com - VP');
            return false;
        }
    }
    
    public PageReference clearErrorMessage()
    {
        return null;
    }
    
    @isTest
    static void testSourceCodeManagementController()
    {
        MProject__c prj = new MProject__c(Name='acme');
        insert prj;
        LoginCredential__c login = new LoginCredential__c(Name='test', Type__c='Sandbox', Username__c='test', Password__c='test', Project__c=prj.Id);
        insert login;
        
        SourceCodeManagementController controller = new SourceCodeManagementController(new ApexPages.StandardController(prj));
        
    }
}