src/objects/MobileDevice__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>DeviceToken__c</fullName>
        <label>Device Token</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DeviceType__c</fullName>
        <inlineHelpText>&quot;ios&quot; or &quot;android&quot;</inlineHelpText>
        <label>Device Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>UserId__c</fullName>
        <label>UserId</label>
        <length>18</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Mobile Device</label>
</CustomObject>

src/objects/MProject__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TimeCard__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>TimeCards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TeamMember__c</fullName>
        <label>Team Member</label>
        <referenceTo>TeamMember__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{0000000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/IOSTimeCardReminderSchedule.cls
/*
 * Scheduled job for time card reminder notification to iOS devices
 */
global class IOSTimeCardReminderSchedule implements Schedulable
{
    global void execute(SchedulableContext SC) 
    {
        MobileNotificationService.NotificationInfo notification = new MobileNotificationService.NotificationInfo(System.now(), true);
        String messageBody = 'Reminder: You don\'t have any time card logged today.';
        String backgroundMessage = '{}';
        Map<String, List<String>> userId2DeviceTokens = MobileNotificationService.getUserId2DeviceTokensByUserIdsAndType(userIdsHaveNoTimeCardToday(), 'ios');
        for(String userId : userId2DeviceTokens.keySet())
        {
            for(String deviceToken : userId2DeviceTokens.get(userId))
            {
                notification.Messages.add(new MobileNotificationService.NotificationMessageInfo(messageBody, deviceToken, backgroundMessage));
            }
        }
        IOSChangeNotificationService iOSChangeNotification = new IOSChangeNotificationService();
        iOSChangeNotification.pushNotification(notification);
    }
    
    private static Set<Id> userIdsHaveNoTimeCardToday()
    {
        Set<Id> userIdsHaveTimeCardToday = new Set<Id>();
        for(TimeCard__c timecard : [select TeamMember__r.User__c from TimeCard__c where Date__c = :System.today() and TeamMember__r.User__r.IsEmployee__c = 1])
        {
            userIdsHaveTimeCardToday.add(timecard.TeamMember__r.User__c);
        }
        Set<Id> userIdsHaveNoTimeCardToday = new Set<Id>();
        for(User user :[select Id from User where Id not in :userIdsHaveTimeCardToday and IsEmployee__c = 1])
        {
            userIdsHaveNoTimeCardToday.add(user.Id);
        }
        return userIdsHaveNoTimeCardToday;
    }

    @isTest
    static void testIOSTimeCardReminderSchedule()
    {
        Set<Id> userIds = new Set<Id>();
        List<User> users = [select Id, Name from User where IsEmployee__c = 1 limit 2];
        for(User user : users)
        {
            userIds.add(user.Id);
        }
        
        MProject__c project = new MProject__c(Name = 'acme');
        insert project;
        TeamMember__c teamMember = new TeamMember__c(Project__c = project.Id, User__c = users[0].Id, Name = 'acme1');
        insert teamMember;
        TimeCard__c timeCard = new TimeCard__c(TeamMember__c = teamMember.Id, Project__c = project.Id, Hours__c = 8, Description__c = 'acme1', Date__c=Date.today());
        insert timeCard;
        
        String deviceToken1 = 'df9351db69d1eab3130c1b9c5a7fb2c87edc04268ae3f1aeb37c2928170f0f8c';
        String deviceToken2 = 'aab24c7cd71c3815487e2bf6fe72272c4d5fc9a5d645441886399fb44bb1167a';
        String deviceType = 'ios';
        List<MobileDevice__c> mobileDevices = new List<MobileDevice__c>();
        for(User user : users)
        {
            mobileDevices.add(new MobileDevice__c(Name = user.Name + '1', UserId__c = user.Id, DeviceToken__c = deviceToken1, DeviceType__c = deviceType));
            mobileDevices.add(new MobileDevice__c(Name = user.Name + '2', UserId__c = user.Id, DeviceToken__c = deviceToken2, DeviceType__c = deviceType));
        }
        insert mobileDevices;
        
        Test.startTest();
        
        Set<Id> userIdsHaveNoTimeCardToday = userIdsHaveNoTimeCardToday();
        for(Id userId : userIdsHaveNoTimeCardToday)
        {
            System.assertNotEquals(users[0].Id, userId);
        }
        
        String jobId = System.schedule('testIOSTimeCardReminderSchedule', '0 0 22 * * ?', new IOSTimeCardReminderSchedule());
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime from CronTrigger where Id = :jobId];
        System.assertEquals('0 0 22 * * ?', ct.CronExpression);
        
        Test.stopTest();
    }
}