src/objects/MProject__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>EndDate__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>StartDate__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UAT</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TimeCard__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>TimeCards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TeamMember__c</fullName>
        <label>Team Member</label>
        <referenceTo>TeamMember__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{0000000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/PerfectAttendanceCreditJobTest.cls
/*
 * Test method for class PerfectAttendanceCreditJob.
 */
@isTest
private class PerfectAttendanceCreditJobTest
{
    //Create user
    private static User user;
    static 
    {
        String ret = 'user' + Math.rint(Math.random() * 100000);
        user = new User();
        user.Email = 'jair.zheng@meginfo.com';
        user.Username = ret + '@testuser.com';
        user.LastName = 'test';
        user.Alias = 'test';
        user.LanguageLocaleKey = 'en_US';
        user.LocaleSidKey = 'en_US';
        user.TimeZoneSidKey = 'America/Chicago';
        user.EmailEncodingKey = 'UTF-8';

        user.UserRoleId = '00E800000013v1n';
        user.ProfileId = '00e8000000183bS';
        user.ManagerId = UserInfo.getUserId();
    }

    @isTest
    static void testSchedule()
    {
        Test.startTest();
        PerfectAttendanceCreditJob schedule = new PerfectAttendanceCreditJob();
        Test.stopTest();

    }
    @isTest
    static void testBatch()
    {
        System.runAs(user)
        {           
            //MProject__c project = TestDataFactory.generateSampleActiveProject('TestProject');
            MProject__c project = new MProject__c(Name='TestProject');
            project.Status__c = 'In Progress';
            project.StartDate__c = Date.today();
            project.EndDate__c = Date.today().addYears(1);
            insert project;

            TeamMember__c teamMember = new TeamMember__c(User__c=user.Id, Project__c=project.Id);
            teamMember.Name = 'acme' + Datetime.now().getTime();
            insert teamMember;

            Date firstDay = Date.newInstance(2014, 6, 1);
            List<TimeCard__c> timecards = new List<TimeCard__c>();
            for(Integer i = 0; i <= 23; i++)
            {
                timecards.add(new TimeCard__c(Project__c = project.Id, TeamMember__c = teamMember.Id, Hours__c = 8, Description__c = 'description' + i, Date__c = firstDay.addDays(i)));
            }
            insert timecards;

            List<WorkDays__c> workdays = new List<WorkDays__c>();
            workdays.add(new WorkDays__c(Name = '2014-1', Year__c = '2014', Month__c = '1', Days__c = '22'));
            workdays.add(new WorkDays__c(Name = '2014-2', Year__c = '2014', Month__c = '2', Days__c = '17'));
            workdays.add(new WorkDays__c(Name = '2014-3', Year__c = '2014', Month__c = '3', Days__c = '21'));
            workdays.add(new WorkDays__c(Name = '2014-4', Year__c = '2014', Month__c = '4', Days__c = '21'));
            workdays.add(new WorkDays__c(Name = '2014-5', Year__c = '2014', Month__c = '5', Days__c = '21'));
            workdays.add(new WorkDays__c(Name = '2014-6', Year__c = '2014', Month__c = '6', Days__c = '20'));
            workdays.add(new WorkDays__c(Name = '2014-7', Year__c = '2014', Month__c = '7', Days__c = '23'));
            workdays.add(new WorkDays__c(Name = '2014-8', Year__c = '2014', Month__c = '8', Days__c = '21'));
            workdays.add(new WorkDays__c(Name = '2014-9', Year__c = '2014', Month__c = '9', Days__c = '22'));
            workdays.add(new WorkDays__c(Name = '2014-10', Year__c = '2014', Month__c = '10', Days__c = '19'));
            workdays.add(new WorkDays__c(Name = '2014-11', Year__c = '2014', Month__c = '11', Days__c = '20'));
            workdays.add(new WorkDays__c(Name = '2014-12', Year__c = '2014', Month__c = '12', Days__c = '23'));
            insert workdays;
            
            Test.startTest();
            PerfectAttendanceCreditJob batch = new PerfectAttendanceCreditJob();
            Database.executeBatch(batch);
            Test.stopTest();

       } 
    }

}