src/objects/MProject__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Score__c.object
<CustomObject>
    <description>In construction.personal count Score.</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Scores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Worth__c</fullName>
        <label>Worth</label>
        <summarizedField>SubScore__c.worth__c</summarizedField>
        <summaryForeignKey>SubScore__c.Score__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Score</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>ScoreNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TimeCard__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>TimeCards</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>TeamMember__c</fullName>
        <label>Team Member</label>
        <referenceTo>TeamMember__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{0000000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MonthlyScoreControlWithTimeCardTest.cls
/*
 * Test method for class ScoreControlWithTimeCard.
 */
@isTest
private class MonthlyScoreControlWithTimeCardTest
{
    @isTest
    static void testSchedule()
    {
        Test.startTest();
        MonthlyScoreControlWithTimeCard schedule = new MonthlyScoreControlWithTimeCard();
        Test.stopTest();

    }
    @isTest
    static void testBatch()
    {
        Test.startTest();
        User user = TestDataFactory.newUser('00e8000000183bS', '00E800000013v1n');
        insert user;
        MProject__c project = TestDataFactory.generateSampleActiveProject('TestProject');
        insert project;
        TeamMember__c teamMember = new TeamMember__c(User__c=user.Id, Project__c=project.Id);
        teamMember.Name = 'acme' + Datetime.now().getTime();
       // TeamMember__c teamMember = TestDataFactory.generateSampleTeamMember(project);
        insert teamMember;
        Score__c score = new Score__c();
        score.User__c = user.Id;
        insert score;
        Date firstDay = Date.newInstance(2014, 6, 1);
        List<TimeCard__c> timecards = new List<TimeCard__c>();
        for(Integer i = 0; i <= 23; i++)
        {
            timecards.add(new TimeCard__c(Project__c = project.Id, TeamMember__c = teamMember.Id, Hours__c = 8, Description__c = 'description' + i, Date__c = firstDay.addDays(i)));
        }
        insert timecards;
        //MonthlyScoreControlWithTimeCard ms = new MonthlyScoreControlWithTimeCard();
        //String jobId = System.schedule('testMonthlyScoreControlWithTimeCard', '0 0 0 1 7 ? 2014', ms);
        MonthlyScoreControlWithTimeCard batch = new MonthlyScoreControlWithTimeCard();
        Database.executeBatch(batch);

        System.assertNotEquals(0.3, [select Worth__c from  Score__c where User__c = :user.Id limit 1].Worth__c);
        Test.stopTest();
        System.assertEquals(0.3, [select Worth__c from  Score__c where User__c = :user.Id limit 1].Worth__c);


    }

}