src/objects/MProject__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Team Members</relationshipLabel>
        <relationshipName>TeamMembers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Role__c</fullName>
        <label>Role</label>
        <picklist>
            <picklistValues>
                <fullName>Customer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Account Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Project Manager</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Consultant</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Development Lead</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Developer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tester</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UI Designer</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/UserHandler.cls
/*
 * A help class for trigger AutoCreateSelfLearningTeamMember.
 */
public class UserHandler
{
    static String SELF_LEARN_PRO = 'Project for self-learning and non-work related hours';
    @future
    public static void createTeamMembers(List<Id> userIds)
    {
        List<TeamMember__c> newMembers = new List<TeamMember__c>();
        List<MProject__c> selfLearnProjects = [select Id, Name from MProject__c where Name = :SELF_LEARN_PRO limit 1];
        List<User> users = [select Id, Name, UserRoleId from User where Id in :userIds];
        if(selfLearnProjects.size() > 0 && users.size() > 0)
        {
            for(User newUser : users)
            {
                newMembers.add(new TeamMember__c(Name = newUser.Name, Project__c = selfLearnProjects[0].Id, User__c = newUser.Id, Role__c = newUser.UserRoleId));
            }
        }
        Database.insert(newMembers, false);
    }
}