src/objects/PrivateKey__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Key__c</fullName>
        <label>Key</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>Private Key</label>
</CustomObject>

src/objects/S3File__c.object
<CustomObject>
    <fields>
        <fullName>FileName__c</fullName>
        <label>File Name</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsPublic__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Public</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>NumberOfDownloads__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Number of Downloads</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>S3Bucket__c</fullName>
        <label>S3 Bucket</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3Key__c</fullName>
        <label>S3 Key</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SizeInBytes__c</fullName>
        <label>Size In Bytes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>S3 File</label>
    <nameField>
        <displayFormat>F{000000}</displayFormat>
        <label>File Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S3 Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/S3FileDownloadControllerTest.cls
/* 
 * Test methods of S3FileDownloadController
 */
@isTest
public class S3FileDownloadControllerTest
{
	@isTest
    static void test()
    {
        PrivateKey__c key1 = new PrivateKey__c(Name='S3AccessKey', Key__c='123');
        PrivateKey__c key2 = new PrivateKey__c(Name='S3SecretKey', Key__c='123');
        insert new List<PrivateKey__c> { key1, key2 };
        S3File__c file = new S3File__c(FileName__c='acme', S3Bucket__c='acme', S3Key__c='acme', SizeInBytes__c=20, IsPublic__c=false);
        insert file;
        
        S3FileDownloadController controller = new S3FileDownloadController(new ApexPages.StandardController(file));
        controller.redirect();
        file = [select Id, NumberOfDownloads__c from S3File__c where Id=:file.Id limit 1];
        System.assertEquals(1, file.NumberOfDownloads__c);
    }
}