src/objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <picklist>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RMB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>DisplayAmount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display Amount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Project</label>
        <referenceTo>MProject__c</referenceTo>
        <relationshipLabel>Quotes</relationshipLabel>
        <relationshipName>Quotes</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q{000000}</displayFormat>
        <label>Quote #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/QuoteLine__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsAdditional__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Additional</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>QuoteLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>Sort Order</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Hours</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RMB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL{0000000}</displayFormat>
        <label>Quote Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuotationService.cls
/*
 * Includes service methods for Quote object
 */
global class QuotationService 
{
    webservice static String cloneQuote(String quoteId)
    {
    	List<Quote__c> quotes = [select Id, DisplayAmount__c, Currency__c, UnitPrice__c, Project__c, Description__c,
    							(select Amount__c, IsAdditional__c, SortOrder__c, Task__c, Unit__c from QuoteLines__r)  
    							from Quote__c where Id=:quoteId limit 1];
    	if(quotes.size() > 0)
    	{
    		Quote__c newQuote = quotes[0].clone(false, false, false, false);
    		insert newQuote;
    		List<QuoteLine__c> newLines = new List<QuoteLine__c>();
    		for(QuoteLine__c line : quotes[0].QuoteLines__r)
    		{
    			newLines.add(new QuoteLine__c(Quote__c=newQuote.Id, Amount__c=line.Amount__c, IsAdditional__c=line.IsAdditional__c, SortOrder__c=line.SortOrder__c, Task__c=line.Task__c, Unit__c=line.Unit__c));
    		}
    		if(newLines.size() > 0)
    		{
    			insert newLines;
    		}
    		return newQuote.Id; 
    	}
    	return null;
    }
    
    @isTest
    static void testCloneQuote()
    {
    	Quote__c quote = new Quote__c();
    	insert quote;
    	cloneQuote(quote.Id);
    }
}