src/objects/Quote__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>TODAY()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DisplayAmount__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display Amount</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>Unit Price</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q{000000}</displayFormat>
        <label>Quote #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/QuoteLine__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>14</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>IsAdditional__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Additional</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Quote__c</fullName>
        <label>Quote</label>
        <referenceTo>Quote__c</referenceTo>
        <relationshipLabel>Quote Lines</relationshipLabel>
        <relationshipName>QuoteLines</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>SortOrder__c</fullName>
        <label>Sort Order</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Task__c</fullName>
        <label>Task</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Unit__c</fullName>
        <label>Unit</label>
        <picklist>
            <picklistValues>
                <fullName>Hours</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Days</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>USD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>RMB</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Quote Line</label>
    <nameField>
        <displayFormat>QL{0000000}</displayFormat>
        <label>Quote Line #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quote Lines</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuotePrintController.cls
/*
 * Controller of page QuotePrint
 */
public with sharing class QuotePrintController 
{
    private Quote__c quoteRecord;
    
    public QuotePrintController(ApexPages.StandardController controller) 
    {
        quoteRecord = (Quote__c)controller.getRecord();
    }
    
    public List<QuoteLine__c> StandardLines
    {
        get
        {
            return [select Id, Name, Task__c, SortOrder__c, Amount__c, Unit__c from QuoteLine__c where Quote__c=:quoteRecord.Id and IsAdditional__c=false order by SortOrder__c];
        }
    }
    
    public List<QuoteLine__c> AdditionalLines
    {
        get
        {
            return [select Id, Name, Task__c, SortOrder__c, Amount__c, Unit__c from QuoteLine__c where Quote__c=:quoteRecord.Id and IsAdditional__c=true order by SortOrder__c];
        }
    }
    
    public String StandardUnit
    {
        get
        {
            if(StandardLines.size() > 0)
            {
                return StandardLines[0].Unit__c;
            }
            else
            {
                return '';
            }
        }
    }
    
    public Decimal Total
    {
        get
        {
            Decimal result = 0;
            if(quoteRecord.DisplayAmount__c == true)
            {
                for(QuoteLine__c line : StandardLines)
                {
                    if(line.Unit__c == 'Hours' || line.Unit__c == 'Days')
                    {
                        Decimal unitPrice = (quoteRecord.UnitPrice__c == null) ? 0 : quoteRecord.UnitPrice__c;
                        Decimal qty = (line.Amount__c == null) ? 0 : line.Amount__c;
                        result += unitPrice * qty;
                    }
                    else
                    {
                        result += (line.Amount__c == null) ? 0 : line.Amount__c;
                    }
                }
            }
            else
            {
                for(QuoteLine__c line : StandardLines)
                {
                    result += (line.Amount__c == null) ? 0 : line.Amount__c;
                }
            }
            return result;
        }
    }
    
    @isTest
    static void testQuotePrintController()
    {
        Quote__c quote = new Quote__c(Date__c=Date.today(), DisplayAmount__c=true, UnitPrice__c=10);
        insert quote;
        QuoteLine__c line1 = new QuoteLine__c(Quote__c=quote.Id, IsAdditional__c=false, Task__c='acme', Amount__c=1, Unit__c='Days');
        insert line1;
        QuoteLine__c line2 = new QuoteLine__c(Quote__c=quote.Id, IsAdditional__c=true, Task__c='acme', Amount__c=1);
        insert line2;
        
        ApexPages.StandardController st = new ApexPages.StandardController(quote);
        QuotePrintController controller = new QuotePrintController(st);
        
        System.assertEquals(1, controller.StandardLines.size());
        System.assertEquals(1, controller.AdditionalLines.size());
        System.assertEquals('Days', controller.StandardUnit);
        System.assertEquals(10, controller.Total);
    }
}