src/objects/S3File__c.object
<CustomObject>
    <fields>
        <fullName>FileName__c</fullName>
        <label>File Name</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3Bucket__c</fullName>
        <label>S3 Bucket</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>S3Key__c</fullName>
        <label>S3 Key</label>
        <length>250</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SizeInBytes__c</fullName>
        <label>Size In Bytes</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>S3 File</label>
    <nameField>
        <displayFormat>F{000000}</displayFormat>
        <label>File Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>S3 Files</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/MeginfoUrlRewriterTest.cls
@isTest
public class MeginfoUrlRewriterTest
{
	@isTest
    static void test()
    {
        S3File__c file = new S3File__c(FileName__c='acme', S3Bucket__c='acme', S3Key__c='acme', SizeInBytes__c=20);
        insert file;
        file = [select Id, Name from S3File__c where Id=:file.Id limit 1];
        MeginfoUrlRewriter rewriter = new MeginfoUrlRewriter();
        PageReference result = rewriter.mapRequestUrl(new PageReference('/f/' + file.Name.substring(1, file.Name.length()) + '?query#hash'));
		System.assert(result.getUrl().contains('S3FileDownload'));
        
        List<PageReference> result2 = rewriter.generateUrlFor(new PageReference[] { new PageReference('/acme')});
        System.assertEquals(1, result2.size());
    }
}