src/objects/Score__c.object
<CustomObject>
    <description>In construction.personal count Score.</description>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Scores</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Worth__c</fullName>
        <label>Worth</label>
        <summarizedField>SubScore__c.worth__c</summarizedField>
        <summaryForeignKey>SubScore__c.Score__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <label>Score</label>
    <nameField>
        <displayFormat>S-{0000}</displayFormat>
        <label>ScoreNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Scores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/SubScore__c.object
<CustomObject>
    <description>In construction.Every change on person Score.</description>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Score__c</fullName>
        <label>Score</label>
        <referenceTo>Score__c</referenceTo>
        <relationshipLabel>SubScores</relationshipLabel>
        <relationshipName>SubScores</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>worth__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Worth</label>
        <precision>8</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>SubScore</label>
    <nameField>
        <displayFormat>SS-{0000000000}</displayFormat>
        <label>SubScoreNumber</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SubScores</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TeamMember__c.object
<CustomObject>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Resource</label>
        <referenceTo>User</referenceTo>
        <relationshipName>TeamMembers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TimeCard__c.object
<CustomObject>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TeamMember__c</fullName>
        <label>Team Member</label>
        <referenceTo>TeamMember__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{0000000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/MonthlyScoreControlWithTimeCard.cls
/*
 * this Schedule used to control score with timecard every month
 */
global class MonthlyScoreControlWithTimeCard implements Database.Batchable<SObject>, Schedulable
{
    private final Map<Integer, Integer> workDaysOf2014 = new Map<Integer, Integer>{ 1 => 20, 2 => 17, 3 => 21, 4 => 21, 5 => 21, 6 => 20, 7 => 23, 8 => 21, 9 => 22, 10 => 19, 11 => 20, 12 => 23 };

    global   Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator([select Id, Name from User]);
    }

    //execute method for batch
    global void execute(Database.BatchableContext BC, List<User> users)
    {
        Date dateNow = Date.today();
        Integer yearNow = dateNow.year();
        Integer lastMonth = dateNow.month()-1;
        Integer daysLastMonth = workDaysOf2014.get(lastMonth);

        Set<Id> userIds = new Set<Id>();

        for(User u : users)
        {
            userIds.add(u.Id);
        }

        //date for sql to select TimeCard where between startDay and endDay
        Date startDay = Date.newInstance(yearNow, lastMonth, 1);
        Date endDay = Date.newInstance(yearNow, lastMonth, daysLastMonth);
        //String startDay = yearNow + '-' + lastMonth + '-01';
        //String endDay = yearNow + '-' + lastMonth + '-' + daysLastMonth;

        //all TimeCards this month
        AggregateResult[] timeCards = [select TeamMember__r.User__r.Id, sum(hours__c) from TimeCard__c where (IsLogatSameDay__c = true) and (Date__c >= :startDay and Date__c <= :endDay) group by TeamMember__r.User__r.Id, Date__c order by Date__c desc];
        List<Score__c> scores = [select User__r.Id, Worth__c, Id from Score__c];

        Map<Id, Integer> allTimeCards = new Map<Id, Integer>();
        Map<Id, Id> allScores = new Map<Id, Id>();

        //keep the userId as key and his/her count of days has timecard this month as value on the map
        for(AggregateResult ar: timeCards)
        {
            if(Integer.valueOf(ar.get('expr0')) >= 6)
            {
                String userIdStr = String.valueOf(ar.get('TeamMember__r.User__r.Id'));
                Id userId = Id.valueOf(userIdStr);
                Integer TimeCardNumber;
                if(allTimeCards.get(userId) == null)
                {
                   TimeCardNumber = 1;
                }
                else
                {
                    TimeCardNumber = allTimeCards.get(userId);
                    TimeCardNumber += 1;
                }
                allTimeCards.put(userId,TimeCardNumber);
            }
        }

        //It is wordy here....
        //keep the userId as key and his/her scoreId  as value on the map
        for(Score__c s : scores)
        {
            allScores.put(s.User__r.Id, s.Id);
        }

        //if timecard meet the condition ,then add his/her score
        Set<Id> uIds = allTimeCards.keySet();
        for(Id i : uIds)
        {
            Integer tmNumber = allTimeCards.get(i);
            if(tmNumber >= daysLastMonth)
            {
                Id scoreId = allScores.get(i);
                if(scoreId  == null)
                {
                    //how to deal with it, um......
                }
                else
                {
                    SubScore__c addScore = new SubScore__c();
                    addScore.Score__c = scoreId;
                    addScore.worth__c = 0.3;
                    addScore.Description__c = 'TimeCard encourage for ' + yearNow + '.' + (lastMonth) ;
                    insert addScore;
                }
            }
        }
    }

    global void finish(Database.BatchableContext BC)
    {
    }

    //execute method for schedule
    global void execute(SchedulableContext SC)
    {
        MonthlyScoreControlWithTimeCard batch = new MonthlyScoreControlWithTimeCard();
        Database.executeBatch(batch, 1);
    }
}