src/objects/TeamMember__c.object
<CustomObject>
    <label>Team Member</label>
    <nameField>
        <label>Team Member Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Team Members</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/TimeCard__c.object
<CustomObject>
    <fields>
        <fullName>Billable__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Billable</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <defaultValue>Today()</defaultValue>
        <label>Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Hours__c</fullName>
        <label>Hours</label>
        <precision>12</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TeamMember__c</fullName>
        <label>Team Member</label>
        <referenceTo>TeamMember__c</referenceTo>
        <relationshipLabel>Time Cards</relationshipLabel>
        <relationshipName>Time_Cards</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
        <writeRequiresMasterRead>true</writeRequiresMasterRead>
    </fields>
    <label>Time Card</label>
    <nameField>
        <displayFormat>TC-{0000000}</displayFormat>
        <label>Time Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Time Cards</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TimeCardDashboardController.cls
/*
* Controller for page TimeCardDashboard
* Test method in LogTimeCardControllerTest class
*/
public without sharing class TimeCardDashboardController 
{
    public TimeCardDashboardController() 
    {
        initData();
    }

    public List<String> TeamMemberHours { get; private set; }

    private void initData()
    {
        // ['Bruce Yue', 60, 19]
        TeamMemberHours = new List<String>();
        String firstRow = '[' + '\'Member\'' + ', ' + '\'Billable\'' + ', ' + '\'Non-Billable\'' + ']';
        TeamMemberHours.add(firstRow);
        Map<String, Decimal> teamMemberToBillableHoursMap = new Map<String, Decimal>();
        Map<String, Decimal> teamMemberToNonBillableHoursMap = new Map<String, Decimal>();
        List<AggregateResult> timeCards = [select sum(Hours__c), Billable__c b, TeamMember__r.Name m from TimeCard__c where  Date__c <= :Date.today() and Date__c >= :Date.today().addDays(-30) GROUP BY TeamMember__r.Name, Billable__c ORDER BY TeamMember__r.Name];
        for(AggregateResult result : timeCards)
        {
            if(result.get('b') == true)
            {
                teamMemberToBillableHoursMap.put((String)result.get('m'), (Decimal)result.get('expr0'));
            }
            if(result.get('b') == false)
            {
                teamMemberToNonBillableHoursMap.put((String)result.get('m'), (Decimal)result.get('expr0'));
            }
        }
        buildTeamMemberHoursList(teamMemberToBillableHoursMap, teamMemberToNonBillableHoursMap);
    }

    private void buildTeamMemberHoursList(Map<String, Decimal> teamMemberToBillableHoursMap, Map<String, Decimal> teamMemberToNonBillableHoursMap)
    {
        // Billed = ['allen', 10], ['aaron', 9], ['bruce', 9]
        // Nonbilled = ['allen', 8], ['jair, 10']
        // All = ['allen', 10, 8], ['aaron', 9, 0], ['bruce', 9, 0], ['jair, 0, 10]
        for(String bMember : teamMemberToBillableHoursMap.keySet())
        {
            String rowData = '[\'' + bMember + '\', ';
            rowData += teamMemberToBillableHoursMap.get(bMember);
            Decimal unbilledHours = teamMemberToNonBillableHoursMap.get(bMember) != null ? teamMemberToNonBillableHoursMap.get(bMember) : 0;
            rowData += ',' + unbilledHours;
            rowData += ']';
            TeamMemberHours.add(rowData);
        }
        for(String nMember : teamMemberToNonBillableHoursMap.keySet())
        {
            if(!teamMemberToBillableHoursMap.containsKey(nMember))
            {
                String rowData = '[\'' + nMember + '\', ';
                rowData += 0;
                rowData += ',' + teamMemberToNonBillableHoursMap.get(nMember);
                rowData += ']';
                TeamMemberHours.add(rowData);
            }
        }
    }
}