src/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>WikiSpace__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wiki Space</label>
        <referenceTo>WikiSpace__c</referenceTo>
        <relationshipLabel>Wiki Pages</relationshipLabel>
        <relationshipName>WikiPages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <displayFormat>P {0000}</displayFormat>
        <label>Page Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wiki Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WikiPageVersion__c.object
<CustomObject>
    <description>Check the history of page</description>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsLatestVersion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Latest Version</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WikiPage__c</fullName>
        <label>Wiki Page</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Page Version</relationshipLabel>
        <relationshipName>WikiPageVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wiki Page Version</label>
    <nameField>
        <displayFormat>PV-{YY}{MM}{DD}-{0000}</displayFormat>
        <label>Page Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wiki Page Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WikiSpace__c.object
<CustomObject>
    <label>Wiki Space</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WikiSpaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WikiSpaceControllerTest.cls
@isTest
public class WikiSpaceControllerTest
{
    private static Integer spaceNumber = 5;
    private static Integer pageNumber = 10;

    static testmethod void test()
    {
        createData();

        WikiSpaceController controller = new WikiSpaceController();
        controller.spaceId = controller.Spaces[1].Id;
        System.assertEquals('space1', controller.SpaceName);
        System.assertEquals(5, controller.Spaces.size());
        System.assertEquals(10, controller.WikiPages.size());
    }

    private static void createData()
    {
        List<WikiSpace__c> spaces = new List<WikiSpace__c>();
        List<WikiPage__c> pages = new List<WikiPage__c>();
        List<WikiPageVersion__c> versions = new List<WikiPageVersion__c>();
        for(Integer i=0; i<spaceNumber; i++)
        {
            spaces.add(new WikiSpace__c(Name = 'space' + i));
        }
        insert spaces;

        for(WikiSpace__c space : spaces)
        {
            for(Integer i=0; i<pageNumber; i++)
            {
                pages.add(new WikiPage__c(WikiSpace__c = space.Id));
            }
        }
        insert pages;

        for(WikiPage__c page : pages)
        {
            versions.add(new WikiPageVersion__c(Title__c = 'title', Body__c = 'body', WikiPage__c = page.Id, IsLatestVersion__c = true));
        }
        insert versions;
    }
}