src/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>LastPublishedDate__c</fullName>
        <label>Last Published Date</label>
        <type>DateTime</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <displayFormat>P {0000}</displayFormat>
        <label>Page Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wiki Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WikiPageVersion__c.object
<CustomObject>
    <description>Check the history of page</description>
    <fields>
        <fullName>IsLatestVersion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Latest Version</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LastPublishedDate__c</fullName>
        <label>Last Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WikiPage__c</fullName>
        <label>Wiki Page</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Page Version</relationshipLabel>
        <relationshipName>WikiPageVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wiki Page Version</label>
    <nameField>
        <displayFormat>PV-{YY}{MM}{DD}-{0000}</displayFormat>
        <label>Page Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wiki Page Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/wikiPageSearchController.cls
public with sharing class wikiPageSearchController 
{
	private ApexPages.StandardSetController searchPageSet;

	public String SearchKey { get; set; }
	public List<WikiPageVersion__c> SearchPages { get; set; }

	public wikiPageSearchController() 
	{
		SearchKey = ApexPages.currentPage().getParameters().get('searchkey');
		if(String.isBlank(SearchKey))
		{
			SearchPages = new List<WikiPageVersion__c>();
		}
		else
		{
			SearchWikiPage();
		}
		
	}

	public void SearchWikiPage()
	{
		if(String.isNotBlank(SearchKey))
        {
            String searchKeyTemp = '%' + SearchKey + '%';

            searchPageSet = new ApexPages.StandardSetController([SELECT Id, Title__c, WikiPage__c, CreatedById, CreatedBy.Name, CreatedBy.FullPhotoUrl, WikiPage__r.LastPublishedDate__c   
                                                               FROM WikiPageVersion__c WHERE IsLatestVersion__c = true and (Title__c like :searchKeyTemp or Tag__c like :searchKeyTemp) ORDER BY WikiPage__r.LastPublishedDate__c DESC limit 100]);
       		searchPageSet.setPageSize(10);
       		SearchPages = (List<WikiPageVersion__c>)searchPageSet.getRecords();
        }       
	}
	public void nextPageOfWikiPageVersion()
	{
		if(searchPageSet.getHasNext())
		{
			searchPageSet.next();
			SearchPages = (List<WikiPageVersion__c>)searchPageSet.getRecords();
		}
	}
	public void previousPageOfWikiPageVersion()
	{
		if(searchPageSet.getHasPrevious())
		{
			searchPageSet.previous();
			SearchPages = (List<WikiPageVersion__c>)searchPageSet.getRecords();
		}
	}
}