src/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>WikiSpace__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wiki Space</label>
        <referenceTo>WikiSpace__c</referenceTo>
        <relationshipLabel>Wiki Pages</relationshipLabel>
        <relationshipName>WikiPages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <displayFormat>P {0000}</displayFormat>
        <label>Page Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wiki Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WikiPageVersion__c.object
<CustomObject>
    <description>Check the history of page</description>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WikiPage__c</fullName>
        <label>Wiki Page</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Page Version</relationshipLabel>
        <relationshipName>WikiPageVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wiki Page Version</label>
    <nameField>
        <displayFormat>PV-{YY}{MM}{DD}-{0000}</displayFormat>
        <label>Page Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wiki Page Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WikiSpace__c.object
<CustomObject>
    <label>Wiki Space</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WikiSpaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WikiNewPageControllerTest.cls
@isTest
public class WikiNewPageControllerTest
{
    @isTest
    public static void testNewPage()
    {
        WikiNewPageController controller = new WikiNewPageController();
        controller.cancel();
        controller.LatestPage.Body__c = 'test';
        controller.LatestPage.Title__c = 'SummerTest';
        controller.save();
        System.assertEquals([select id from WikiPage__c].size(),1);
        controller.LatestPage = null;
        controller.save();
    }

    @isTest
    public static void testEditPage()
    {
        WikiDataFactory dataFactory = new WikiDataFactory();
        dataFactory.createWikiPagesWithSpaces(3,5,true);

        PageReference pageRef = new ApexPages.PageReference('/apex/WikiNewPageTest');
        Id pageId = [select id from WikiPage__c limit 1].Id;
        pageRef.getParameters().put('id',pageId);
        Test.setCurrentPage(pageRef);
        //Test pages with pageVersion
        WikiNewPageController controller = new WikiNewPageController();
        controller.WikiSpaceId = [select Id from Wikispace__c limit 1][0].Id;
        controller.LatestPage.Body__c = 'test';
        controller.LatestPage.Title__c = 'SummerTest';
        controller.save();

        //Test with Space exits.
        List<SelectOption> spaceOptions = controller.SpaceOptions;
        controller.getUserInfo();
        System.assertEquals(spaceOptions.size(), 4);
        System.assertEquals([select id from WikiPageVersion__c].size(),16);

        //Test pages without page Version and the WikiSpaceId is null
        delete [select Id from WikiPageVersion__c];
        PageReference pageRef2 = new ApexPages.PageReference('/apex/WikiNewPageTest');
        pageRef2.getParameters().put('spaceid', null);
        Test.setCurrentPage(pageRef2);
        WikiNewPageController controller2 = new WikiNewPageController();

        //Test with no Space.
        delete [select Id from WikiSpace__c];
        List<SelectOption> spaceOptions2 = controller.SpaceOptions;
        controller.cancel();


        controller.LatestPage = null;
        controller.save();
    }
}