src/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>FirstPublishedDate__c</fullName>
        <label>First Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>LastPublishedDate__c</fullName>
        <label>Last Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>TotalPageVersion__c</fullName>
        <label>Total Page Version</label>
        <summaryForeignKey>WikiPageVersion__c.WikiPage__c</summaryForeignKey>
        <summaryOperation>count</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>WikiSpace__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wiki Space</label>
        <referenceTo>WikiSpace__c</referenceTo>
        <relationshipLabel>Wiki Pages</relationshipLabel>
        <relationshipName>WikiPages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <displayFormat>P {0000}</displayFormat>
        <label>Page Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wiki Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WikiPageVersion__c.object
<CustomObject>
    <description>Check the history of page</description>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>FirstPublishedDate__c</fullName>
        <label>First Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>IsLatestVersion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Latest Version</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>tag for wiki page</description>
        <inlineHelpText>Please use the whitespace or comma add more labels</inlineHelpText>
        <label>Label</label>
        <picklist>
            <picklistValues>
                <fullName>Apex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visualforce</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>LastPublishedDate__c</fullName>
        <label>Last Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>PublishStatus__c</fullName>
        <label>Publish Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Online</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Archived</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>VersionNumber__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Version Number</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WikiPage__c</fullName>
        <label>Wiki Page</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Page Version</relationshipLabel>
        <relationshipName>WikiPageVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wiki Page Version</label>
    <nameField>
        <displayFormat>PV-{YY}{MM}{DD}-{0000}</displayFormat>
        <label>Page Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wiki Page Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WikiSpace__c.object
<CustomObject>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Wiki Space</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WikiSpaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WikiSpaceController.cls
public with sharing class WikiSpaceController
{
	private String spaceID;
	private String pageID;

	public List<WikiPage__c> WikiPages { get; set; }
	//public List<WikiPageVersion__c> wikiVersion;
	public List<WikiSpace__c> space;

	private ApexPages.StandardSetController wikiPageSet;
	public Boolean HasNext { get; set; }
	public Boolean HasPrevious { get; set; }
	public Integer CurrentPage { get; set; }
	public Integer PageSize { get; set; }
	public Integer PageNum { get; set; }

	public WikiSpaceController()
	{
		//WikiPage = new WikiPage__c();
		//pages = new LIst<WikiPage__c>();
		spaceID = ApexPages.CurrentPage().getParameters().get('Id');
		initSpaceSet();
		
	}

	public WikiPage__c WikiPage { get; set; }
	public WikiPageVersion__c WikiPageVersion { get; set; }

	public List<WikiSpace__c> getSpace()
	{
		space =	[select Id, Name, Name__c, Summary__c from WikiSpace__c 
		where  Id = :spaceID];
		return space;
	}
	public String getSpaceId()
	{
		return spaceID;
	}

	
	public void nextWikiPages()
	{
		wikiPageSet.next();
		WikiPages = (List<WikiPage__c>) wikiPageSet.getRecords();

		HasPrevious = wikiPageSet.getHasPrevious();
		HasNext = wikiPageSet.getHasNext();
		CurrentPage = wikiPageSet.getPageNumber();
	}

	
	public void priviousWikiPages()
	{
		wikiPageSet.previous();
		WikiPages = (List<WikiPage__c>) wikiPageSet.getRecords();

		HasPrevious = wikiPageSet.getHasPrevious();
		HasNext = wikiPageSet.getHasNext();
		CurrentPage = wikiPageSet.getPageNumber();
	}

	private void initSpaceSet()
	{
		PageSize = 4;
		wikiPageSet = new ApexPages.StandardSetController([select Id, Name, WikiSpace__c, TotalPageVersion__c,
		LastPublishedDate__c,FirstPublishedDate__c, (select Id, Name, Body__c, FirstPublishedDate__c, 
	    IsLatestVersion__c, Label__c, LastPublishedDate__c, PublishStatus__c,
	    Title__c, VersionNumber__c, WikiPage__c from WikiPageVersions__r order by VersionNumber__c desc limit 4) from WikiPage__c 
		where WikiSpace__c = :spaceID]);
		wikiPageSet.setPageSize(pageSize);
		WikiPages = (List<WikiPage__c>) wikiPageSet.getRecords();

		HasPrevious = wikiPageSet.getHasPrevious();
		HasNext = wikiPageSet.getHasNext();
		CurrentPage = wikiPageSet.getPageNumber();

		PageNum = (Integer)(Math.round(wikiPageSet.getResultSize()/wikiPageSet.getPageSize())+1);
	}

}