src/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>LastPublishedDate__c</fullName>
        <label>Last Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WikiSpace__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wiki Space</label>
        <referenceTo>WikiSpace__c</referenceTo>
        <relationshipLabel>Wiki Pages</relationshipLabel>
        <relationshipName>WikiPages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <displayFormat>P {0000}</displayFormat>
        <label>Page Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wiki Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WikiPageVersion__c.object
<CustomObject>
    <description>Check the history of page</description>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsLatestVersion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Latest Version</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Label__c</fullName>
        <description>tag for wiki page</description>
        <inlineHelpText>Please use the whitespace or comma add more labels</inlineHelpText>
        <label>Label</label>
        <picklist>
            <picklistValues>
                <fullName>Apex</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Visualforce</fullName>
            </picklistValues>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>LastPublishedDate__c</fullName>
        <label>Last Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>VersionNumber__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Version Number</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WikiPage__c</fullName>
        <label>Wiki Page</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Page Version</relationshipLabel>
        <relationshipName>WikiPageVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wiki Page Version</label>
    <nameField>
        <displayFormat>PV-{YY}{MM}{DD}-{0000}</displayFormat>
        <label>Page Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wiki Page Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WikiSpace__c.object
<CustomObject>
    <label>Wiki Space</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WikiSpaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WikiViewPageController.cls
/**
 * A controller for WikiViewPage
 */
public with sharing class WikiViewPageController
{
    private String pageId;
    public PublishedPage PubPage { get; set; }
    public Boolean IsVoted { get; set; } 
    public String VoteParam { get; set; }
    Public String testStr { get; set; }

    public WikiViewPageController()
    {
        IsVoted = false;
        pageId = ApexPages.currentPage().getParameters().get('id');
        getPubishedPage();
    }    

    private void getPubishedPage()
    {
        List<WikiPage__c> publishedPages = [select Id, WikiSpace__r.Name,WikiSpace__c, CreatedById, LastModifiedById, LastPublishedDate__c,
                                            (select Id, Body__c, Label__c, Title__c, CreatedById,LikeVotes__c, UnlikeVotes__c, LastModifiedDate from WikiPageVersions__r
                                             where IsLatestVersion__c = true)
                                           from WikiPage__c where Id = :pageId];
        if(publishedPages.size() > 0)
        {
            PubPage = new PublishedPage(publishedPages[0]);  

            List<VoteForPage__c> votes = [select Id from VoteForPage__c where WikiPageVersion__c =:PubPage.WikiPageVersion.Id and CreatedById =: UserInfo.getUserId()];

            if(votes.size() > 0)
            {
                IsVoted = true;
            }       
        }        
    }

    public void vote()
    {
        try
        {
            if(!isVoted && VoteParam != null)
            {
                VoteForPage__c votePage = new VoteForPage__c();
                votePage.LikeOrNotLike__c = VoteParam.toLowerCase();
                votePage.WikiPageVersion__c = PubPage.WikiPageVersion.Id;
                insert votePage;
                IsVoted = true;

                if(VoteParam.equalsIgnoreCase('like'))
                {
                    PubPage.WikiPageVersion.LikeVotes__c = PubPage.WikiPageVersion.LikeVotes__c == null ? 1 : PubPage.WikiPageVersion.LikeVotes__c + 1;
                }
                else if(VoteParam.equalsIgnoreCase('unlike'))
                {
                    PubPage.WikiPageVersion.UnlikeVotes__c = PubPage.WikiPageVersion.UnlikeVotes__c == null ? 1 : PubPage.WikiPageVersion.UnlikeVotes__c + 1;
                }
                update PubPage.WikiPageVersion;
            }
        }
        catch(Exception e3)
        {
            
        }
        
    }

    public List<WikiPageVersion__c> getVoteData() 
    {
         return [select Id, VersionNumber__c, LikeVotes__c, UnlikeVotes__c from WikiPageVersion__c where WikiPage__c =:PubPage.WikiPage.Id order by VersionNumber__c asc limit 4];
    }
    
    public class PublishedPage
    {
        public PublishedPage(WikiPage__c wikiPage)
        {
            this.WikiPage = wikiPage;
            this.WikiPageVersion = wikiPage.WikiPageVersions__r[0];
        }

        public WikiPage__c WikiPage { get; set; }
        public WikiPageVersion__c WikiPageVersion { get; set; }
    }
}