src/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>LastPublishedDate__c</fullName>
        <label>Last Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WikiSpace__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wiki Space</label>
        <referenceTo>WikiSpace__c</referenceTo>
        <relationshipLabel>Wiki Pages</relationshipLabel>
        <relationshipName>WikiPages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <displayFormat>P {0000}</displayFormat>
        <label>Page Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wiki Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WikiPageVersion__c.object
<CustomObject>
    <description>Check the history of page</description>
    <fields>
        <fullName>Body__c</fullName>
        <label>Body</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>IsLatestVersion__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Latest Version</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LastPublishedDate__c</fullName>
        <label>Last Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>VersionNumber__c</fullName>
        <defaultValue>1</defaultValue>
        <label>Version Number</label>
        <precision>4</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>WikiPage__c</fullName>
        <label>Wiki Page</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Page Version</relationshipLabel>
        <relationshipName>WikiPageVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wiki Page Version</label>
    <nameField>
        <displayFormat>PV-{YY}{MM}{DD}-{0000}</displayFormat>
        <label>Page Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wiki Page Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WikiSpace__c.object
<CustomObject>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Wiki Space</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WikiSpaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WikiDataFactory.cls
/*
 * To create data for WikiNewPageControllerTest, WikiHomeControllerTest and WikiViewPageControllerTest class
 */
@isTest
public class WikiDataFactory
{
    public List<WikiSpace__c> createWikiSpaces(Integer spaceCount)
    {
        List<WikiSpace__c> spaces = new List<WikiSpace__c>();
        for(Integer i = 0; i < spaceCount; i++)
        {
            WikiSpace__c space = new WikiSpace__c(Name = 'test', Summary__c = 'this is a test record.');
            spaces.add(space);
        }
        insert spaces;
        return spaces;
    }

    public List<WikiPage__c> createWikiPagesWithSpaces(Integer spacesCount, Integer pageCount, Boolean withPageVersion)
    {
        List<WikiSpace__c> spaces = createWikiSpaces(spacesCount);
        List<WikiPage__c> pages = new List<WikiPage__c>();
        List<FeedItem> feedItems = new List<FeedItem>();
        for(WikiSpace__c space :spaces)
        {
            for(Integer i = 0; i < pageCount; i++)
            {
                WikiPage__c page = new WikiPage__c(Title__c = 'title'+i, WikiSpace__c = space.Id);
                pages.add(page);
            }
        }
        insert pages;
        Boolean flage = false;
        for(WikiPage__c page : pages) 
        {
            if(flage)
            {
                FeedItem feedItem1 = new FeedItem(ParentId = page.Id, Body = 'testBody');
                FeedItem feedItem2 = new FeedItem(ParentId = page.Id, Body = 'testBody');
                feedItems.add(feedItem1);
                feedItems.add(feedItem2);
                flage = false;
            }
            else
            {
                FeedItem feedItem = new FeedItem(ParentId = page.Id, Body = 'testBody2');
                feedItems.add(feedItem);
                flage = true;
            }
        }
        insert feedItems;
        if(withPageVersion)
        {
            createWikiPageVersions(pages);
        }
        return pages;
    }
    public void createWikiPageVersions(List<WikiPage__c> pages)
    {
        List<WikiPageVersion__c> pageVersions = new List<WikiPageVersion__c>();
        for(WikiPage__c page : pages)
        {
            WikiPageVersion__c pageVersion = new WikiPageVersion__c(Title__c = 'title', Body__c = 'body', WikiPage__c = page.Id, IsLatestVersion__c = true,VersionNumber__c = 1, LastPublishedDate__c = System.Now());
            pageVersions.add(pageVersion);
        }
        insert pageVersions;
    }
}