src/objects/WikiPage__c.object
<CustomObject>
    <fields>
        <fullName>LastPublishedDate__c</fullName>
        <label>Last Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WikiSpace__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Wiki Space</label>
        <referenceTo>WikiSpace__c</referenceTo>
        <relationshipLabel>Wiki Pages</relationshipLabel>
        <relationshipName>WikiPages</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Wiki Page</label>
    <nameField>
        <displayFormat>P {0000}</displayFormat>
        <label>Page Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wiki Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/WikiPageVersion__c.object
<CustomObject>
    <description>Check the history of page</description>
    <fields>
        <fullName>LastPublishedDate__c</fullName>
        <label>Last Published Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>WikiPage__c</fullName>
        <label>Wiki Page</label>
        <referenceTo>WikiPage__c</referenceTo>
        <relationshipLabel>Page Version</relationshipLabel>
        <relationshipName>WikiPageVersions</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Wiki Page Version</label>
    <nameField>
        <displayFormat>PV-{YY}{MM}{DD}-{0000}</displayFormat>
        <label>Page Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Wiki Page Versions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/WikiSpace__c.object
<CustomObject>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Wiki Space</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WikiSpaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WikiHomeControllerTest.cls
/*
 *Test class for WikiHomeController 
 */
@isTest
public class WikiHomeControllerTest
{
	@isTest
	public static void testContructorAndSimpleMethods()
	{
		// Load the data for the test
		WikiDataFactory dataFactory = new WikiDataFactory();
		dataFactory.createWikiPagesWithSpaces(5, 6,true);

		PageReference pageRef = new ApexPages.PageReference('/apex/WikiHome');
		Test.setCurrentPage(pageRef);
		WikiHomeController controller = new WikiHomeController();
		List<WikiSpace__c> spaceOptions = controller.MySpaces;
		List<WikiPageVersion__c> pagesOptions = controller.MyPages; 
		controller.loadMorePopularPages();
		List<WikiPage__c> pages = [select LastPublishedDate__c from WikiPage__c limit 3];
		List<WikiPage__c> modifiedFiledPages = new List<WikiPage__c>();
		Date testDate = date.newinstance(2014,12,12);
		for(WikiPage__c wikipage : pages)
		{
			wikipage.LastPublishedDate__c = testDate;
			modifiedFiledPages.add(wikipage);
		}
		update modifiedFiledPages;
		controller.getWikiPageFieldLabelMap();

	}

	@isTest
	public static void testCreateNewSpace()
	{	
		WikiHomeController controller = new WikiHomeController();		

		controller.NewSpace.Summary__c = 'test';
		controller.createNewSpace();
		controller.NewSpace.Name = 'test';
		controller.createNewSpace();

		List<WikiSpace__c> spaces = [select Id from WikiSpace__c];
		System.assertEquals(spaces.size(), 1);		
	}
}