src/objects/WikiSpace__c.object
<CustomObject>
    <fields>
        <fullName>Summary__c</fullName>
        <label>Summary</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Wiki Space</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WikiSpaces</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/WikiHomeController.cls
/**
 *
 */
public with sharing class WikiHomeController
{
    public WikiHomeController()
    {
    	NewSpace = new WikiSpace__c();
    	NewSpaceSuccess = false;
        getPopularPages();
    }

    public WikiSpace__c NewSpace { get; set; }
    public Boolean NewSpaceSuccess { get; set; }

    public String getPopularPages()
    {
        return '';
    }

    public void createNewSpace()
    {
    	try
    	{
    	    insert NewSpace;
    	    NewSpaceSuccess = true;
    	}
    	catch(Exception ex)
    	{
    		ApexPages.addMessages(ex);
    	}
    }

    @isTest
    static void testWikiHome()
    {
    	WikiHomeController controller = new WikiHomeController();
    	controller.NewSpace.Name__c = 'test';
    	controller.NewSpace.Summary__c = 'test';
    	controller.createNewSpace();
    	system.assertEquals('test', [select Name__c from WikiSpace__c WHERE id = :controller.NewSpace.Id][0].Name__c);
    }
}